version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: velas_postgres
    restart: always
    environment:
      POSTGRES_USER: velas_user
      POSTGRES_PASSWORD: velas_password
      POSTGRES_DB: velas_db
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
